import { BaseIconProps } from "./BaseIcon";
import { ChevronUpOutline, ChevronUpFilled } from "./icons/ChevronUp";
import { ChevronDownOutline, ChevronDownFilled } from "./icons/ChevronDown";
import { ChevronLeftOutline, ChevronLeftFilled } from "./icons/ChevronLeft";
import { ChevronRightOutline, ChevronRightFilled } from "./icons/ChevronRight";
import { CloseOutline, CloseFilled } from "./icons/Close";
import { MenuOutline, MenuFilled } from "./icons/Menu";
import { MoreHorizontalOutline, MoreHorizontalFilled } from "./icons/MoreHorizontal";
import { MoreVerticalOutline, MoreVerticalFilled } from "./icons/MoreVertical";
import { AddOutline, AddFilled } from "./icons/Add";
import { RemoveOutline, RemoveFilled } from "./icons/Remove";
import { CheckOutline, CheckFilled } from "./icons/Check";
import { EditOutline, EditFilled } from "./icons/Edit";
import { DeleteOutline, DeleteFilled } from "./icons/Delete";
import { SearchOutline, SearchFilled } from "./icons/Search";
import { FilterOutline, FilterFilled } from "./icons/Filter";
import { SortOutline, SortFilled } from "./icons/Sort";
import { RefreshOutline, RefreshFilled } from "./icons/Refresh";
import { InfoOutline, InfoFilled } from "./icons/Info";
import { SuccessOutline, SuccessFilled } from "./icons/Success";
import { WarningOutline, WarningFilled } from "./icons/Warning";
import { ErrorOutline, ErrorFilled } from "./icons/Error";
import { LoadingOutline, LoadingFilled } from "./icons/Loading";
import { ShowOutline, ShowFilled } from "./icons/Show";
import { HideOutline, HideFilled } from "./icons/Hide";
import { ExpandOutline, ExpandFilled } from "./icons/Expand";
import { CollapseOutline, CollapseFilled } from "./icons/Collapse";
import { CheckboxCheckedOutline, CheckboxCheckedFilled } from "./icons/CheckboxChecked";
import { CheckboxUncheckedOutline, CheckboxUncheckedFilled } from "./icons/CheckboxUnchecked";
import { CheckboxIndeterminateOutline, CheckboxIndeterminateFilled } from "./icons/CheckboxIndeterminate";
import { RadioCheckedOutline, RadioCheckedFilled } from "./icons/RadioChecked";
import { RadioUncheckedOutline, RadioUncheckedFilled } from "./icons/RadioUnchecked";
import { SettingsOutline, SettingsFilled } from "./icons/Settings";
import { UserOutline, UserFilled } from "./icons/User";
import { HomeOutline, HomeFilled } from "./icons/Home";
import { CalendarOutline, CalendarFilled } from "./icons/Calendar";
import { FolderOutline, FolderFilled } from "./icons/Folder";
import { FileOutline, FileFilled } from "./icons/File";

export type IconComponent = (props: BaseIconProps) => JSX.Element;

export const iconRegistry = {
  "chevron-up": { outline: ChevronUpOutline, filled: ChevronUpFilled },
  "chevron-down": { outline: ChevronDownOutline, filled: ChevronDownFilled },
  "chevron-left": { outline: ChevronLeftOutline, filled: ChevronLeftFilled },
  "chevron-right": { outline: ChevronRightOutline, filled: ChevronRightFilled },
  "close": { outline: CloseOutline, filled: CloseFilled },
  "menu": { outline: MenuOutline, filled: MenuFilled },
  "more-horizontal": { outline: MoreHorizontalOutline, filled: MoreHorizontalFilled },
  "more-vertical": { outline: MoreVerticalOutline, filled: MoreVerticalFilled },
  "add": { outline: AddOutline, filled: AddFilled },
  "remove": { outline: RemoveOutline, filled: RemoveFilled },
  "check": { outline: CheckOutline, filled: CheckFilled },
  "edit": { outline: EditOutline, filled: EditFilled },
  "delete": { outline: DeleteOutline, filled: DeleteFilled },
  "search": { outline: SearchOutline, filled: SearchFilled },
  "filter": { outline: FilterOutline, filled: FilterFilled },
  "sort": { outline: SortOutline, filled: SortFilled },
  "refresh": { outline: RefreshOutline, filled: RefreshFilled },
  "info": { outline: InfoOutline, filled: InfoFilled },
  "success": { outline: SuccessOutline, filled: SuccessFilled },
  "warning": { outline: WarningOutline, filled: WarningFilled },
  "error": { outline: ErrorOutline, filled: ErrorFilled },
  "loading": { outline: LoadingOutline, filled: LoadingFilled },
  "show": { outline: ShowOutline, filled: ShowFilled },
  "hide": { outline: HideOutline, filled: HideFilled },
  "expand": { outline: ExpandOutline, filled: ExpandFilled },
  "collapse": { outline: CollapseOutline, filled: CollapseFilled },
  "checkbox-checked": { outline: CheckboxCheckedOutline, filled: CheckboxCheckedFilled },
  "checkbox-unchecked": { outline: CheckboxUncheckedOutline, filled: CheckboxUncheckedFilled },
  "checkbox-indeterminate": { outline: CheckboxIndeterminateOutline, filled: CheckboxIndeterminateFilled },
  "radio-checked": { outline: RadioCheckedOutline, filled: RadioCheckedFilled },
  "radio-unchecked": { outline: RadioUncheckedOutline, filled: RadioUncheckedFilled },
  "settings": { outline: SettingsOutline, filled: SettingsFilled },
  "user": { outline: UserOutline, filled: UserFilled },
  "home": { outline: HomeOutline, filled: HomeFilled },
  "calendar": { outline: CalendarOutline, filled: CalendarFilled },
  "folder": { outline: FolderOutline, filled: FolderFilled },
  "file": { outline: FileOutline, filled: FileFilled },
} as const;
